services:
  php-fpm:
    image: pplulee/tronpower-php:latest
    container_name: tronpower-php
    volumes:
      - ./web:/var/www/html
    depends_on:
      - mariadb
    networks:
      - tronpower-network
    restart: always

  nginx:
    image: nginx:latest
    container_name: tronpower-nginx
    ports:
      - "127.0.0.1:7593:80"
    volumes:
      - ./data/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./web:/var/www/html
    depends_on:
      - php-fpm
    networks:
      - tronpower-network
    restart: always

  redis:
    image: redis:latest
    container_name: tronpower-redis
    volumes:
      - ./data/redis:/data
    networks:
      - tronpower-network
    restart: always

  mariadb:
    image: mariadb:latest
    container_name: tronpower-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: tronpower # 请修改为自己的密码
      MYSQL_DATABASE: tronpower
    volumes:
      - ./data/mariadb/data:/var/lib/mysql
      - ./data/mariadb/conf:/etc/mysql/conf.d
    networks:
      - tronpower-network
    restart: always

  backend:
    image: pplulee/tronpower:latest
    container_name: tronpower-backend
    volumes:
      - ./data/backend-config.toml:/app/config.toml
    depends_on:
      - nginx
    networks:
      - tronpower-network

networks:
  tronpower-network:
    driver: bridge
